name: Build and Push Docker Image

on:
  push:
    branches: [main]

jobs:
  mlflow-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.7"

      - name: Install Dependencies
        run: |
          pip install mlflow==2.19.0 scikit-learn pandas dagshub matplotlib seaborn

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run Training to Generate Model
        run: |
          # Menjalankan training agar folder 'mlruns' tercipta
          python MLProject/modelling.py
        env:
          DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}

      - name: Build Docker Image from Last Run
        run: |
          mlflow models build-docker -m "runs:/$(mlflow search-runs --experiment-name 'Diabetes_Classification_Advanced' --max-results 1 --output csv | tail -n 1 | cut -d, -f1)/model" -n "${{ secrets.DOCKERHUB_USERNAME }}/diabetes-app:latest" --enable-mlserver

      - name: Push to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/diabetes-app:latest
