name: Build and Push Docker Image

on:
  push:
    branches: [main]

jobs:
  mlflow-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.7"

      - name: Install MLflow and Dependencies
        run: |
          pip install mlflow==2.19.0 scikit-learn pandas dagshub matplotlib seaborn

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          # Membangun docker dari folder MLProject
          mlflow models build-docker -m "MLProject" -n "${{ secrets.DOCKERHUB_USERNAME }}/diabetes-app:latest" --enable-mlserver
        env:
          DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}

      - name: Push to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/diabetes-app:latest
