name: Build and Push Docker Image

on:
  push:
    branches: [main]

jobs:
  mlflow-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.7"

      - name: Install Dependencies
        run: |
          pip install mlflow==2.19.0 scikit-learn pandas dagshub matplotlib seaborn

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run Training to Generate Model
        run: |
          python MLProject/modelling.py
        env:
          DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}

      - name: Build Docker Image from Last Run
        run: |
          # Menggunakan script python pendek untuk mengambil RUN_ID terbaru secara akurat
          RUN_ID=$(python -c "import mlflow; exp = mlflow.get_experiment_by_name('Diabetes_Classification_Advanced'); runs = mlflow.search_runs(experiment_ids=[exp.experiment_id], max_results=1, order_by=['attributes.start_time DESC']); print(runs.iloc[0]['run_id'])")
          echo "Building Docker for RUN_ID: $RUN_ID"
          mlflow models build-docker -m "runs:/$RUN_ID/model" -n "${{ secrets.DOCKERHUB_USERNAME }}/diabetes-app:latest" --enable-mlserver
        env:
          MLFLOW_TRACKING_URI: https://dagshub.com/hqee/eksperimen_sml_haqi-dhiya.mlflow
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}

      - name: Push to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/diabetes-app:latest
